version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: suave-server
    restart: unless-stopped
    ports:
      - 8022:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf